version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./requirements-dev.txt:/app/requirements-dev.txt
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    depends_on:
      - mqtt
      - redis
    command: >
      bash -c "uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend

  mqtt:
    image: eclipse-mosquitto:2.0.15
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # MQTT over WebSocket
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    command: mosquitto -c /mosquitto-no-auth.conf

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Uncomment if you need a database in the future
  # db:
  #   image: postgres:14-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: mostwo
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  mosquitto_data:
  mosquitto_log:
  redis_data:
  # postgres_data:
